# Basis-Image
FROM debian:12-slim as base

# Aktualisierung der Paketliste und Installation von notwendigen Tools
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y bash jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY scripts/write-raw-file.sh /app/write-raw-file.sh
RUN chmod +x /app/write-raw-file.sh
CMD [ "/app/write-raw-file.sh" ]
